// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from "./Accordion/index.svelte";
import BluxBlock from "./BluxBlock/index.svelte";
import BluxCarousel from "./BluxCarousel/index.svelte";
import BluxCollection from "./BluxCollection/index.svelte";
import BluxEmbed from "./BluxEmbed/index.svelte";
import BluxGallery from "./BluxGallery/index.svelte";
import BluxGrid from "./BluxGrid/index.svelte";
import BluxMedia from "./BluxMedia/index.svelte";
import BluxMediaText from "./BluxMediaText/index.svelte";
import BluxSection from "./BluxSection/index.svelte";
import BluxTable from "./BluxTable/index.svelte";
import BluxText from "./BluxText/index.svelte";
import Carousel from "./Carousel/index.svelte";
import CollectionList from "./CollectionList/index.svelte";
import Gallery from "./Gallery/index.svelte";
import GridBand from "./GridBand/index.svelte";
import Hero from "./Hero/index.svelte";
import LeadText from "./LeadText/index.svelte";
import LocationMap from "./LocationMap/index.svelte";
import MediaFull from "./MediaFull/index.svelte";
import MediaText from "./MediaText/index.svelte";
import RichText from "./RichText/index.svelte";
import SectionGrid from "./SectionGrid/index.svelte";
import SplitFeature from "./SplitFeature/index.svelte";
import TextColumns from "./TextColumns/index.svelte";
import TitleBand from "./TitleBand/index.svelte";

export const components = {
  accordion: Accordion,
  blux_block: BluxBlock,
  blux_carousel: BluxCarousel,
  blux_collection: BluxCollection,
  blux_embed: BluxEmbed,
  blux_gallery: BluxGallery,
  blux_grid: BluxGrid,
  blux_media: BluxMedia,
  blux_media_text: BluxMediaText,
  blux_section: BluxSection,
  blux_table: BluxTable,
  blux_text: BluxText,
  carousel: Carousel,
  collection_list: CollectionList,
  gallery: Gallery,
  grid_band: GridBand,
  hero: Hero,
  lead_text: LeadText,
  location_map: LocationMap,
  media_full: MediaFull,
  media_text: MediaText,
  rich_text: RichText,
  section_grid: SectionGrid,
  split_feature: SplitFeature,
  text_columns: TextColumns,
  title_band: TitleBand,
};
